# Regenerates db/seed.sql from the verb lexicon (data/verbs.ts) and the
# claimable backlog (data/priority-words.ts). Run from the repo root:
#   powershell -ExecutionPolicy Bypass -File scripts/gen-seed.ps1
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

$raw = Get-Content "data/verbs.ts" -Raw
$verbMatches = [regex]::Matches($raw, 'slug:"([^"]+)",\s*word:"([^"]+)",\s*category:"([^"]+)",.*?synonyms:\[([^\]]*)\]')

$alpha = [regex]'^[a-z]+$'
$covered = [ordered]@{}   # token -> [pscustomobject]@{ slug; category }
foreach ($m in $verbMatches) {
  $slug = $m.Groups[1].Value
  $word = $m.Groups[2].Value.ToLower()
  $cat  = $m.Groups[3].Value
  $syns = [regex]::Matches($m.Groups[4].Value, '"([^"]+)"') | ForEach-Object { $_.Groups[1].Value.ToLower() }
  $tokens = @($word, $slug) + $syns
  foreach ($t in $tokens) {
    if ($alpha.IsMatch($t) -and -not $covered.Contains($t)) {
      $covered[$t] = [pscustomobject]@{ slug = $slug; category = $cat }
    }
  }
}

# backlog words
$plRaw = Get-Content "data/priority-words.ts" -Raw
$backlog = [regex]::Matches($plRaw, '"([a-z]+)"') | ForEach-Object { $_.Groups[1].Value } |
  Where-Object { -not $covered.Contains($_) } | Select-Object -Unique

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("-- GENERATED by scripts/gen-seed.ps1 -- do not edit by hand.")
[void]$sb.AppendLine("-- Seeds the curated core action lexicon + one demo animation per covered word.")
[void]$sb.AppendLine("-- The full English dictionary (dwyl words_alpha.txt) is bulk-loaded separately.")
[void]$sb.AppendLine("BEGIN TRANSACTION;")
[void]$sb.AppendLine("")

$id = 0
$wordId = @{}
[void]$sb.AppendLine("-- words (covered) -----------------------------------------------------------")
foreach ($t in $covered.Keys) {
  $id++; $wordId[$t] = $id
  $c = $covered[$t]
  [void]$sb.AppendLine("INSERT INTO word (id, word, in_lexicon, verb_slug, category) VALUES ($id, '$t', 1, '$($c.slug)', '$($c.category)');")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- words (open backlog) ------------------------------------------------------")
foreach ($t in $backlog) {
  $id++; $wordId[$t] = $id
  [void]$sb.AppendLine("INSERT INTO word (id, word, in_lexicon) VALUES ($id, '$t', 1);")
}
[void]$sb.AppendLine("")

[void]$sb.AppendLine("-- demo users ----------------------------------------------------------------")
[void]$sb.AppendLine("INSERT INTO app_user (id, email, display_name, oauth_provider) VALUES (1, 'demo@animationdictionary.xyz', 'Demo Animator', 'google');")
[void]$sb.AppendLine("")

[void]$sb.AppendLine("-- one demo animation per covered word --------------------------------------")
$animId = 0
foreach ($t in $covered.Keys) {
  $animId++
  $title = (Get-Culture).TextInfo.ToTitleCase($t)
  [void]$sb.AppendLine("INSERT INTO animation (id, word_id, author_id, title, rigs, status, price_usd) VALUES ($animId, $($wordId[$t]), 1, '$title', '[""UE5"",""Unity"",""Mixamo""]', 'approved', 1);")
}
[void]$sb.AppendLine("")

[void]$sb.AppendLine("-- demo tags + a claim on 'jump' --------------------------------------------")
[void]$sb.AppendLine("INSERT INTO tag (id, name) VALUES (1, 'scared'), (2, 'back'), (3, 'side');")
if ($wordId.ContainsKey('jump')) {
  $jumpAnim = ([System.Linq.Enumerable]::ToList([string[]]$covered.Keys)).IndexOf('jump') + 1
  [void]$sb.AppendLine("INSERT INTO animation_tag (animation_id, tag_id) VALUES ($jumpAnim, 1), ($jumpAnim, 2), ($jumpAnim, 3);")
  [void]$sb.AppendLine("INSERT INTO claim (id, word_id, user_id, rigs, tags, status) VALUES (1, $($wordId['jump']), 1, '[""UE5""]', '[""scared jump"",""back jump"",""side jump""]', 'submitted');")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("COMMIT;")

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $root "db/seed.sql"), $sb.ToString(), $utf8NoBom)
Write-Host ("seed.sql written: {0} covered words, {1} backlog words, {2} animations" -f $covered.Count, ($backlog | Measure-Object).Count, $animId)
